ALTER TABLE `groups` MODIFY balance BIGINT NOT NULL DEFAULT 0;
ALTER TABLE withdrawal_requests MODIFY amount BIGINT NOT NULL;
ALTER TABLE loans MODIFY amount BIGINT NOT NULL, MODIFY amount_repaid BIGINT NOT NULL DEFAULT 0;
